// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/custos-machina/backend/internal/app"
	"github.com/custos-machina/backend/internal/config"
	"github.com/custos-machina/backend/internal/modules/auth"
	"github.com/custos-machina/backend/internal/modules/health"
	"github.com/custos-machina/backend/internal/modules/identity"
	"github.com/custos-machina/backend/internal/modules/rbac"
	"github.com/custos-machina/backend/internal/modules/resources"
	"github.com/custos-machina/backend/internal/modules/setup"
	"github.com/custos-machina/backend/internal/pkg/jwt"
	"github.com/custos-machina/backend/internal/server"
)

// Injectors from wire.go:

// InitializeServer 由 wire 生成到 wire_gen.go（go generate ./...）。
func InitializeServer() (*server.Server, func(), error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, nil, err
	}
	handler := health.NewHandler()
	db, cleanup, err := app.ProvideDB(configConfig)
	if err != nil {
		return nil, nil, err
	}
	userRepository := identity.NewUserRepository(db)
	imBindingRepository := identity.NewIMBindingRepository(db)
	settingsRepository := identity.NewSettingsRepository(db)
	manager := jwt.NewManager(configConfig)
	cipher := auth.ProvideCipher(configConfig)
	authService := auth.NewAuthService(userRepository, imBindingRepository, settingsRepository, manager, configConfig, cipher)
	authHandler := auth.NewHandler(authService)
	userService := identity.NewUserService(userRepository)
	setupHandler := setup.NewHandler(userService)
	identityHandler := identity.NewHandler(userService)
	syncedEnforcer, cleanup2, err := rbac.NewEnforcer(db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	service := rbac.NewService(syncedEnforcer)
	rbacHandler := rbac.NewHandler(service, userRepository)
	serverRepository := resources.NewServerRepository(db)
	groupRepository := resources.NewGroupRepository(db)
	resourcesService := resources.NewService(serverRepository, groupRepository, db, cipher)
	collector, cleanup3, err := resources.NewCollector(db, serverRepository, resourcesService)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	resourcesHandler := resources.NewHandler(resourcesService, collector)
	modules := app.ProvideModules(handler, authHandler, setupHandler, identityHandler, rbacHandler, resourcesHandler)
	authMiddleware := auth.ProvideAuthMiddleware(authService)
	middlewareDeps := rbac.MiddlewareDeps{
		Enforcer: syncedEnforcer,
		Users:    userRepository,
	}
	handlerFunc := rbac.ProvideMiddleware(middlewareDeps)
	engine := server.NewEngine(configConfig, modules, authMiddleware, handlerFunc)
	serverServer := server.New(configConfig, engine)
	return serverServer, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
